name: CI
on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
        with:
          disable-checks: outputs,execution_count
